gui:
  showIcons: true
# log customize
git:
  branchLogCmd: "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}} --"
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  allBranchesLogCmds:
    - git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all
customCommands:
  - key: "C"
    context: "files"
    command: "git commit -v -t ~/.config/git/commit_template_with_prompt.txt"
    description: "Commit changes using git editor"
    output: terminal
